baseURL = 'https://fengwz17.github.io'
title = 'Weizhi Feng'

# multi-language support
defaultContentLanguage = 'en'

# enable git info
enableGitInfo = true

# disable taxonomy, term and RSS (which removes categories, tags and index.xml)
disableKinds = ["taxonomy", "term", "RSS"]

[module]
  [[module.imports]]
    path = 'github.com/geekifan/zero-academic-page'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    title = 'Zero'

    [languages.en.params]
      author = "Weizhi Feng"
      description = "Ph.D Student in [ISCAS](https://iscas.ac.cn). Focusing on [Formal Verification](https://en.wikipedia.org/wiki/Formal_verification)(Software/Hardware/LLM)."
      motto = "."
    
    [[languages.en.menu.main]]
      name = 'About Me'
      url = '#about-me'
      weight = 1
    [[languages.en.menu.main]]
      name = 'News'
      url = '#news'
      weight = 2
    [[languages.en.menu.main]]
      name = 'Publications'
      url = '#publications'
      weight = 3
    [[languages.en.menu.main]]
      name = 'Honors and Awards'
      url = '#honors-and-awards'
      weight = 4
    [[languages.en.menu.main]]
      name = 'Educations'
      url = '#educations'
      weight = 5
    [[languages.en.menu.main]]
      name = 'Talks'
      url = '#talks'
      weight = 6
    [[languages.en.menu.main]]
      name = 'Internships'
      url = '#internships'
      weight = 7
      
[params]
  profilePicture = "images/profile.png"
  enableDarkMode = true
  
  [[params.social]]
    name = "github"
    url = "https://github.com/fengwz17"
    icon = "fab fa-github"
  [[params.social]]
    name = "google scholar"
    url = "https://scholar.google.com/citations?user=DXxyULUAAAAJ&hl=en&authuser=1&oi=ao"
    icon = "fab fa-google-scholar"
  [[params.social]]
    name = "email"
    url = "fengwzATios.ac.cn"
    icon = "fas fa-envelope"

[build]
  writeStats = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
